export enum HUD_SENSORS_DETAIL_NAME
{
    MIN_VALUE="MIN_VALUE",
	MAX_VALUE="MAX_VALUE",
	OFFSET="OFFSET",
	SENSIBILITY="SENSIBILITY",
	PRECISION="PRECISION",
	RESOLUTION="RESOLUTION",
	COLOR_DEPTH="COLOR_DEPTH",
	DELAY="DELAY"
}